[package]
name = "microdb"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.2.1"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.22.0", features = ["sync"] }
futures = "0.3"

[lib]
crate-type = ["lib"]