[package]
name = "sample"
version = "0.1.0"
edition = "2021"

[dependencies]
microdb = { path = "../microdb" }
serde = { version = "1.0", features = ["derive"] }
bincode = "1.2.1"
tokio = { version = "1.22.0", features = ["sync", "macros", "rt", "rt-multi-thread"] }